/* Business Invoice & Receipt Manager - vanilla JS + IndexedDB. Records carry businessId for future multi-business support. */
const STORES=['customers','products','invoices','receipts','payments','expenses','settings'];
let db,P={},D={},page='dashboard';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const r2=n=>Math.round((+n+Number.EPSILON)*100)/100;
const money=n=>(P.cur||'GHS')+' '+r2(n||0).toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
const today=()=>new Date().toISOString().slice(0,10);
const pad=(p,n)=>p+String(n).padStart(6,'0');
function toast(m,err){const d=document.createElement('div');d.textContent=m;if(err)d.className='e';$('#toast').append(d);setTimeout(()=>d.remove(),3500)}
/* ---- IndexedDB layer ---- */
const open_=()=>new Promise((res,rej)=>{const r=indexedDB.open('bim',1);r.onupgradeneeded=()=>STORES.forEach(s=>r.result.createObjectStore(s,{keyPath:'id'}));r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)});
const tx=(s,m,f)=>new Promise((res,rej)=>{const t=db.transaction(s,m),q=f(t.objectStore(s));t.oncomplete=()=>res(q&&q.result);t.onerror=t.onabort=()=>rej(t.error)});
const put=async(s,v)=>{try{v.businessId='default';await tx(s,'readwrite',o=>o.put(v));await load()}catch(e){toast('Database error: '+e.message,1);throw e}};
const del=async(s,id)=>{await tx(s,'readwrite',o=>o.delete(id));await load()};
async function load(){for(const s of STORES)D[s]=await tx(s,'readonly',o=>o.getAll());
 P=D.settings.find(x=>x.id=='profile')||{id:'profile',name:'KDB Enterprise',phone:'0244797413 / 0208977296',cur:'GHS',ip:'INV-',rp:'REC-',tax:0,terms:'Due on receipt',foot:'Thank you for your business!',iseq:0,rseq:0,theme:'light',fmt:'a4'};
 document.documentElement.dataset.theme=P.theme}
/* ---- helpers ---- */
const by=(s,id)=>D[s].find(x=>x.id==id)||{};
const stat=i=>i.total>0&&i.paid>=i.total-0.005?'Paid':i.due<today()?'Overdue':i.paid>0?'Partial':'Unpaid';
function calc(items,disc,tax){let sub=0;items.forEach(i=>sub+=i.qty*i.price*(1-i.disc/100));sub=r2(sub);disc=Math.min(r2(disc),sub);const t=r2((sub-disc)*tax/100);return{sub,disc,tax:t,total:r2(sub-disc+t)}}
function modal(title,html,onSave){const d=document.createElement('dialog');d.innerHTML=`<form method="dialog"><h3>${title}</h3>${html}<div class="bar"><button class="p">Save</button><button type="button" id="x">Cancel</button></div></form>`;
 document.body.append(d);d.showModal();d.querySelector('#x').onclick=()=>d.close();d.onclose=()=>d.remove();
 d.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const ok=await onSave(Object.fromEntries(new FormData(e.target)),d);if(ok!==false){d.close();render()}}catch(x){toast(x.message,1)}};return d}
const fld=(n,l,v='',t='text',x='')=>`<label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}" ${x}>`;
const sel=(n,l,opts,v)=>`<label>${l}</label><select name="${n}">${opts.map(o=>{const[a,b]=Array.isArray(o)?o:[o,o];return`<option value="${esc(a)}" ${a==v?'selected':''}>${esc(b)}</option>`}).join('')}</select>`;
function table(cols,rows,emptyMsg){if(!rows.length)return`<div class="empty">${emptyMsg||'Nothing here yet.'}</div>`;return`<div class="tw"><table><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</table></div>`}
const btn=(t,f,a,c='')=>`<button class="s ${c}" onclick="${f}('${a}')">${t}</button>`;
/* ---- views ---- */
const NAV=['dashboard','invoices','receipts','customers','products','payments','expenses','reports','settings'];
const V={};
V.dashboard=()=>{const inv=D.invoices,sum=(a,f)=>r2(a.reduce((s,x)=>s+f(x),0)),t=today(),m=t.slice(0,7);
 const sales=sum(inv,i=>i.total),rec=sum(D.payments,p=>p.amount),exp=sum(D.expenses,e=>e.amount);
 const c=(l,v)=>`<div class="card"><span>${l}</span><b>${v}</b></div>`;
 const paid=inv.filter(i=>stat(i)=='Paid').length;
 const top={};inv.forEach(i=>i.items.forEach(x=>top[x.name]=(top[x.name]||0)+x.qty*x.price));
 const tops=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,5),mx=Math.max(1,...tops.map(x=>x[1]));
 return`<div class="bar"><button class="p" onclick="invForm()">+ New Invoice</button><button class="p" onclick="payForm()">+ New Receipt</button><button onclick="custForm()">Add Customer</button><button onclick="prodForm()">Add Product</button><button onclick="go('invoices')">View Invoices</button></div>
 <div class="grid">${c('Total sales',money(sales))}${c('Received',money(rec))}${c('Outstanding',money(sales-rec))}${c('Today',money(sum(inv.filter(i=>i.date==t),i=>i.total)))}${c('This month',money(sum(inv.filter(i=>i.date.startsWith(m)),i=>i.total)))}${c('Invoices',inv.length)}${c('Receipts',D.receipts.length)}${c('Customers',D.customers.length)}${c('Products',D.products.length)}${c('Expenses',money(exp))}</div>
 <div class="grid"><div class="card"><span>Paid vs unpaid</span><b>${paid} / ${inv.length-paid}</b></div><div class="card"><span>Top sellers</span>${tops.map(([n,v])=>`<div>${esc(n)}<div style="background:var(--pri);height:8px;border-radius:4px;width:${v/mx*100}%"></div></div>`).join('')||'<br>No data'}</div></div>
 <h3>Recent invoices</h3>${table(['No.','Customer','Total','Status'],inv.slice(-5).reverse().map(i=>[i.no,esc(by('customers',i.cid).name),money(i.total),`<span class="pill ${stat(i)}">${stat(i)}</span>`]),'No invoices yet.')}`};
V.customers=()=>`<div class="bar"><button class="p" onclick="custForm()">+ Add Customer</button></div>`+table(['ID','Name','Phone','Email','Balance',''],D.customers.map(c=>{const bal=D.invoices.filter(i=>i.cid==c.id).reduce((s,i)=>s+i.total-i.paid,0);return[c.code,esc(c.name),esc(c.phone),esc(c.email),money(bal),btn('Edit','custForm',c.id)+btn('Del','delC',c.id,'d')]}),'No customers yet.');
window.custForm=id=>{const c=by('customers',id);modal(id?'Edit customer':'Add customer',fld('name','Name',c.name,'text','required')+fld('phone','Phone',c.phone)+fld('email','Email',c.email,'email')+fld('address','Address',c.address)+fld('taxid','Tax ID',c.taxid)+fld('notes','Notes',c.notes),async f=>{if(!f.name.trim())throw Error('Name required');await put('customers',{...c,...f,id:c.id||uid('c'),code:c.code||'CUST-'+String(D.customers.length+1).padStart(4,'0'),added:c.added||today()})})};
window.delC=async id=>{if(D.invoices.some(i=>i.cid==id))return toast('Customer has invoices; cannot delete',1);if(confirm('Delete this customer?')){await del('customers',id);render()}};
V.products=()=>`<div class="bar"><button class="p" onclick="prodForm()">+ Add Product</button></div>`+table(['Name','Category','Price','Stock',''],D.products.map(p=>[esc(p.name),esc(p.cat),money(p.price),p.type=='Service'?'—':`<span class="${p.stock<=p.low?'low':''}">${p.stock}${p.stock<=p.low?' ⚠ low':''}</span>`,btn('Edit','prodForm',p.id)+btn('Del','delP',p.id,'d')]),'No products yet.');
window.prodForm=id=>{const p=by('products',id);modal(id?'Edit product':'Add product',fld('name','Name',p.name,'text','required')+fld('cat','Category',p.cat)+sel('type','Type',['Product','Service'],p.type)+fld('unit','Unit',p.unit||'pcs')+fld('price','Selling price',p.price,'number','step=0.01 min=0 required')+fld('cost','Cost price',p.cost||0,'number','step=0.01 min=0')+fld('tax','Tax %',p.tax||0,'number','step=0.01 min=0')+fld('stock','Stock',p.stock||0,'number','min=0')+fld('low','Low-stock level',p.low??5,'number','min=0'),async f=>{if(!f.name.trim()||+f.price<0)throw Error('Invalid name or price');['price','cost','tax','stock','low'].forEach(k=>f[k]=+f[k]);await put('products',{...p,...f,id:p.id||uid('p')})})};
window.delP=async id=>{if(confirm('Delete this product?')){await del('products',id);render()}};
V.invoices=()=>`<div class="bar"><button class="p" onclick="invForm()">+ New Invoice</button></div>`+table(['No.','Date','Customer','Total','Paid','Balance','Status',''],D.invoices.slice().reverse().map(i=>[i.no,i.date,esc(by('customers',i.cid).name),money(i.total),money(i.paid),money(i.total-i.paid),`<span class="pill ${stat(i)}">${stat(i)}</span>`,btn('Print','printInv',i.id)+btn('Pay','payForm',i.id)+btn('Edit','invForm',i.id)+btn('Del','delI',i.id,'d')]),'No invoices yet.');
window.invForm=id=>{if(!D.customers.length)return toast('Add a customer first',1);const i=id?by('invoices',id):{items:[{}],disc:0,tax:P.tax,date:today(),notes:'',terms:P.terms,paid:0};
 const prods=[['','— custom item —'],...D.products.map(p=>[p.id,p.name])];
 const rows=()=>i.items.map(x=>`<div class="row"><select class="pr">${prods.map(([a,b])=>`<option value="${a}" ${a==x.pid?'selected':''}>${esc(b)}</option>`).join('')}</select><input class="qt" type="number" min="0.01" step="any" value="${x.qty||1}"><input class="up" type="number" min="0" step="0.01" value="${x.price||0}"><input class="ds" type="number" min="0" max="100" value="${x.disc||0}" title="Disc %"><button type="button" class="rm">✕</button></div>`).join('');
 const read=()=>$$('#rows .row').map(r=>{const p=by('products',r.querySelector('.pr').value);return{pid:p.id||'',name:p.name||'Custom item',qty:+r.querySelector('.qt').value,price:+r.querySelector('.up').value,disc:Math.min(100,Math.max(0,+r.querySelector('.ds').value))}}).filter(x=>x.qty>0&&x.price>=0);
 const d=modal(id?'Edit invoice '+i.no:'New invoice',sel('cid','Customer',D.customers.map(c=>[c.id,c.name]),i.cid)+fld('date','Date',i.date,'date','required')+fld('due','Due date',i.due||today(),'date','required')+'<label>Items: product · qty · price · disc%</label><div id="rows">'+rows()+'</div><button type="button" id="add">+ Item</button>'+fld('disc','Invoice discount (amount)',i.disc,'number','min=0 step=0.01')+fld('tax','Tax %',i.tax,'number','min=0 step=0.01')+fld('notes','Notes',i.notes)+fld('terms','Terms',i.terms)+'<div class="card" id="tot"></div>',async f=>{
  const items=read();if(!items.length)throw Error('Add at least one valid item');const c=calc(items,+f.disc,+f.tax);if(c.total<=0)throw Error('Invoice total must be above zero. Set the price of each item (Products → Edit) or type it in.');
  if(i.id&&i.paid>c.total+0.004)throw Error('Total cannot be below amount already paid');
  let no=i.no;if(!i.id){const seq=P.iseq+1;no=pad(P.ip,seq);if(D.invoices.some(x=>x.no==no))throw Error('Duplicate invoice number');await put('settings',{...P,iseq:seq})}
  await put('invoices',{...i,id:i.id||uid('i'),no,cid:f.cid,date:f.date,due:f.due,items,disc:c.disc,tax:+f.tax,taxAmt:c.tax,sub:c.sub,total:c.total,notes:f.notes,terms:f.terms})});
 const upd=()=>{const q=n=>d.querySelector(`[name=${n}]`).value,c=calc(read(),+q('disc'),+q('tax'));$('#tot').innerHTML=`Subtotal ${money(c.sub)} · Discount ${money(c.disc)} · Tax ${money(c.tax)}<b>Total ${money(c.total)}</b>`};
 d.addEventListener('input',upd);
 d.addEventListener('change',e=>{if(e.target.classList.contains('pr')){const p=by('products',e.target.value);if(p.id)e.target.parentNode.querySelector('.up').value=p.price;upd()}});
 d.addEventListener('click',e=>{if(e.target.id=='add'){$('#rows').insertAdjacentHTML('beforeend',$('#rows .row').outerHTML);upd()}if(e.target.classList.contains('rm')&&$$('#rows .row').length>1){e.target.parentNode.remove();upd()}});upd()};
window.delI=async id=>{if(D.payments.some(p=>p.iid==id))return toast('Invoice has payments; cannot delete',1);if(confirm('Delete this invoice?')){await del('invoices',id);render()}};
V.receipts=()=>table(['No.','Date','Customer','Invoice','Amount','Method',''],D.receipts.slice().reverse().map(r=>[r.no,r.date,esc(by('customers',r.cid).name),by('invoices',r.iid).no||'—',money(r.amount),r.method,btn('Print','printRec',r.id)]),'No receipts yet. Record a payment to create one.');
V.payments=()=>`<div class="bar"><button class="p" onclick="payForm()">+ Record payment</button></div><div class="grid"><div class="card"><span>Total payments</span><b>${money(D.payments.reduce((s,p)=>s+p.amount,0))}</b></div><div class="card"><span>Today</span><b>${money(D.payments.filter(p=>p.date==today()).reduce((s,p)=>s+p.amount,0))}</b></div></div>`+table(['Date','Customer','Invoice','Amount','Method','Ref'],D.payments.slice().reverse().map(p=>[p.date,esc(by('customers',p.cid).name),by('invoices',p.iid).no,money(p.amount),p.method,esc(p.ref)]),'No payments yet.');
/* Recording a payment creates a payment + linked receipt and updates the invoice's paid amount (status derives from it) */
window.payForm=iid=>{const op=D.invoices.filter(i=>i.total-i.paid>0.004);if(!op.length)return toast('No unpaid invoices',1);
 const cur=iid&&by('invoices',iid).id?iid:op[0].id;
 modal('Record payment / receipt',sel('iid','Invoice',op.map(i=>[i.id,`${i.no} – ${by('customers',i.cid).name} (bal ${money(i.total-i.paid)})`]),cur)+fld('amount','Amount received','','number','step=0.01 min=0.01 required')+fld('date','Date',today(),'date','required')+sel('method','Method',['Cash','Mobile Money','Bank Transfer','Card','Cheque','Other'])+fld('ref','Reference')+fld('notes','Notes'),async f=>{
  const inv=by('invoices',f.iid),amt=r2(f.amount);if(!(amt>0))throw Error('Enter a valid amount');if(amt>r2(inv.total-inv.paid)+0.004)throw Error('Amount exceeds balance due');
  const seq=P.rseq+1,no=pad(P.rp,seq);if(D.receipts.some(r=>r.no==no))throw Error('Duplicate receipt number');await put('settings',{...P,rseq:seq});
  const base={cid:inv.cid,iid:inv.id,amount:amt,date:f.date,method:f.method,ref:f.ref,notes:f.notes};
  await put('payments',{id:uid('pay'),...base});await put('receipts',{id:uid('r'),no,...base,balanceAfter:r2(inv.total-inv.paid-amt)});await put('invoices',{...inv,paid:r2(inv.paid+amt)});toast('Receipt '+no+' created')})};
V.expenses=()=>`<div class="bar"><button class="p" onclick="expForm()">+ Add expense</button></div>`+table(['Date','Category','Description','Amount',''],D.expenses.slice().reverse().map(e=>[e.date,e.category,esc(e.description),money(e.amount),btn('Del','delE',e.id,'d')]),'No expenses yet.');
window.expForm=()=>modal('Add expense',fld('date','Date',today(),'date','required')+sel('category','Category',['Transport','Utilities','Rent','Salaries','Stock','Maintenance','Marketing','Other'])+fld('description','Description')+fld('amount','Amount','','number','step=0.01 min=0.01 required')+sel('method','Method',['Cash','Mobile Money','Bank Transfer','Card'])+fld('supplier','Supplier'),async f=>{await put('expenses',{id:uid('e'),...f,amount:r2(f.amount)})});
window.delE=async id=>{if(confirm('Delete expense?')){await del('expenses',id);render()}};
V.reports=()=>{const sum=(a,f)=>r2(a.reduce((s,x)=>s+f(x),0)),g=(k,a)=>{const o={};a.forEach(x=>{const key=k(x);o[key]=(o[key]||0)+x.total});return Object.entries(o).sort().reverse()};
 const rp=(t,rows)=>`<h3>${t}</h3>`+table(['Period','Sales'],rows.map(([a,b])=>[esc(a),money(b)]),'No data.');const inc=sum(D.payments,p=>p.amount),exp=sum(D.expenses,e=>e.amount);
 return`<button onclick="print()">Print report</button><div class="grid"><div class="card"><span>Income</span><b>${money(inc)}</b></div><div class="card"><span>Expenses</span><b>${money(exp)}</b></div><div class="card"><span>Profit estimate</span><b>${money(inc-exp)}</b></div></div>`+rp('Daily sales',g(i=>i.date,D.invoices).slice(0,14))+rp('Monthly sales',g(i=>i.date.slice(0,7),D.invoices))+rp('By customer',g(i=>by('customers',i.cid).name,D.invoices))+`<h3>Overdue</h3>`+table(['No.','Due','Balance'],D.invoices.filter(i=>stat(i)=='Overdue').map(i=>[i.no,i.due,money(i.total-i.paid)]),'None overdue.')};
V.settings=()=>{const f=(n,l,t='text')=>fld(n,l,P[n],t);return`<form id="pf" class="card">${f('name','Business name')}${f('address','Address')}${f('phone','Phone')}${f('email','Email')}${f('web','Website')}${f('taxno','Tax/VAT no.')}${f('cur','Currency code')}${f('ip','Invoice prefix')}${f('rp','Receipt prefix')}${f('tax','Default tax %','number')}${f('terms','Payment terms')}${f('foot','Footer message')}${sel('theme','Theme',['light','dark'],P.theme)}${sel('fmt','Receipt format',[['a4','A4'],['thermal','Thermal']],P.fmt)}<label>Logo</label><input type="file" id="logo" accept="image/*">${P.logo?`<img src="${P.logo}" height="50">`:''}<div class="bar"><button class="p">Save settings</button></div></form>
 <div class="card bar"><button onclick="backup()">Backup data (JSON)</button><button onclick="$('#rf').click()">Restore data</button><input id="rf" type="file" accept=".json" hidden onchange="restore(this.files[0])"><button onclick="loadServices()">Load KDB services</button><button onclick="seed()">Load sample data</button><button class="d" onclick="wipe(1)">Remove sample data</button><button class="d" onclick="wipe()">Erase ALL data</button></div>`};
document.addEventListener('submit',e=>{if(e.target.id!='pf')return;e.preventDefault();const f=Object.fromEntries(new FormData(e.target));delete f.logo;f.tax=+f.tax||0;const file=$('#logo').files[0];
 const set=async l=>{await put('settings',{...P,...f,logo:l??P.logo});toast('Saved');render()};if(file){const r=new FileReader();r.onload=()=>set(r.result);r.readAsDataURL(file)}else set()});
/* ---- print / PDF (browser "Save as PDF") ---- */
function doc(body,thermal){const w=open('','_blank');if(!w)return toast('Allow pop-ups to print',1);const hd=`<div style="display:flex;gap:12px;align-items:center;border-bottom:2px solid #0f766e;padding-bottom:8px">${P.logo?`<img src="${P.logo}" height="50">`:''}<div><b style="font-size:18px">${esc(P.name)}</b><br>${esc(P.address||'')} ${esc(P.phone||'')} ${esc(P.email||'')}<br>${P.taxno?'Tax no: '+esc(P.taxno):''}</div></div>`;
 w.document.write(`<html><head><title>Document</title><style>body{font:14px sans-serif;margin:${thermal?'4px':'24px'};${thermal?'width:72mm':''}}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ddd;padding:6px;text-align:left}@page{size:${thermal?'80mm auto':'A4'};margin:10mm}</style></head><body>${hd}${body}<p style="text-align:center;margin-top:20px">${esc(P.foot||'')}</p></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
window.printInv=id=>{const i=by('invoices',id),c=by('customers',i.cid);doc(`<h2>INVOICE ${i.no}</h2><p>Date: ${i.date} · Due: ${i.due}<br><b>${esc(c.name)}</b><br>${esc(c.address||'')} ${esc(c.phone||'')} ${esc(c.email||'')}</p><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Disc%</th><th>Amount</th></tr>${i.items.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${x.disc}</td><td>${money(x.qty*x.price*(1-x.disc/100))}</td></tr>`).join('')}</table><p style="text-align:right">Subtotal ${money(i.sub)}<br>Discount ${money(i.disc)}<br>Tax ${money(i.taxAmt)}<br><b>Total ${money(i.total)}</b><br>Paid ${money(i.paid)}<br><b>Balance ${money(i.total-i.paid)}</b></p><p>${esc(i.notes||'')}<br><small>${esc(i.terms||'')}</small></p>`)};
window.printRec=id=>{const r=by('receipts',id),c=by('customers',r.cid);doc(`<h2>RECEIPT ${r.no}</h2><p>Date: ${r.date}<br>Customer: <b>${esc(c.name)}</b><br>Invoice: ${by('invoices',r.iid).no||'—'}<br>Method: ${r.method} ${esc(r.ref||'')}</p><h3>Amount received: ${money(r.amount)}</h3><p>Remaining balance: ${money(r.balanceAfter)}</p><p style="margin-top:40px">Authorized signature: ____________</p>`,P.fmt=='thermal')};
/* ---- backup / restore ---- */
window.backup=()=>{const b=new Blob([JSON.stringify({app:'bim',version:1,date:new Date().toISOString(),data:D},null,1)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`business-backup-${today()}.json`;a.click();toast('Backup downloaded')};
window.restore=async f=>{try{const j=JSON.parse(await f.text());if(j.app!='bim'||!j.data||STORES.some(s=>!Array.isArray(j.data[s])))throw Error('Not a valid backup file');
 if(!confirm('This REPLACES all current data with the backup. Continue?'))return;for(const s of STORES){await tx(s,'readwrite',o=>o.clear());for(const v of j.data[s])await tx(s,'readwrite',o=>o.put(v))}await load();toast('Restore complete');render()}catch(e){toast('Restore failed: '+e.message,1)}};
window.wipe=async sample=>{if(!confirm(sample?'Remove sample data?':'Erase ALL data? Make a backup first!'))return;for(const s of STORES)for(const v of D[s])if(!sample||v.sample)await tx(s,'readwrite',o=>o.delete(v.id));await load();toast('Done');render()};
window.seed=async()=>{const cs=['Kofi Mensah Ltd','Ama Serwaa','Accra Traders','Yaw Boateng','Takoradi Foods'].map((n,k)=>({id:'sc'+k,code:'CUST-S'+k,name:n,phone:'024000000'+k,email:'',added:today(),sample:1}));
 const ps=['Rice 50kg','Cooking oil','Sugar','Consulting hour','Delivery','Notebook','Pens (box)','Printer paper','Soap','Water (case)'].map((n,k)=>({id:'sp'+k,name:n,cat:k%2?'Goods':'General',type:k==3||k==4?'Service':'Product',unit:'pcs',price:20+k*15,cost:10+k*8,tax:0,stock:50,low:5,sample:1}));
 for(const c of cs)await put('customers',c);for(const p of ps)await put('products',p);
 for(let k=0;k<5;k++){const it=[{pid:ps[k].id,name:ps[k].name,qty:2+k,price:ps[k].price,disc:0}],c=calc(it,0,0),paid=k%2?c.total:0;
  await put('settings',{...P,iseq:P.iseq+1});const no=pad(P.ip,P.iseq);
  await put('invoices',{id:'si'+k,no,cid:cs[k].id,date:today(),due:today(),items:it,disc:0,tax:0,taxAmt:0,sub:c.sub,total:c.total,paid,notes:'',terms:P.terms,sample:1});
  if(paid){await put('settings',{...P,rseq:P.rseq+1});await put('payments',{id:'sy'+k,cid:cs[k].id,iid:'si'+k,amount:paid,date:today(),method:'Cash',sample:1});await put('receipts',{id:'sr'+k,no:pad(P.rp,P.rseq),cid:cs[k].id,iid:'si'+k,amount:paid,date:today(),method:'Cash',balanceAfter:0,sample:1})}}
 await put('expenses',{id:'se1',date:today(),category:'Transport',description:'Fuel',amount:80,sample:1});toast('Sample data loaded');render()};
/* ---- KDB Enterprise starter services (prices 0: edit in Products) ---- */
const SERVICES=[['SAV prints','Large format','sq ft'],['Flexy prints','Large format','sq ft'],['PVC prints','Large format','sq ft'],['Wallpaper prints','Large format','sq ft'],['One way vision prints','Large format','sq ft'],['Banner','Printing','sq ft'],['Flyers','Printing','pcs'],['Stickers','Printing','pcs'],['Billboard','Printing','sq ft'],['T-shirt printing','Printing','pcs'],['Cap printing','Printing','pcs'],['Car branding','Printing','job'],['Photocopies','Printing','page'],['Video editing','Media','job'],['Photo shooting','Media','job'],['Graphic design','Media','job'],['Wedding invitations','Design','pcs'],['Picture framing','Other','pcs'],['Stoning','Other','pcs']];
window.loadServices=async()=>{let n=0;for(const[name,cat,unit]of SERVICES)if(!D.products.some(p=>p.name==name)){await put('products',{id:uid('p'),name,cat,type:'Service',unit,price:0,cost:0,tax:0,stock:0,low:0});n++}toast(n+' services added. Set their prices in Products.');render()};
/* ---- shell ---- */
window.go=p=>{page=p;location.hash=p;render()};
function render(){$('#nav').innerHTML=NAV.map(n=>`<a href="#${n}" class="${n==page?'on':''}" style="text-transform:capitalize">${n}</a>`).join('');$('#view').innerHTML=`<h2 style="text-transform:capitalize">${page}</h2>`+V[page]();$('#side').classList.remove('open');filter()}
function filter(){const q=$('#q').value.toLowerCase();$$('#view tr').forEach((r,n)=>{if(n)r.style.display=r.textContent.toLowerCase().includes(q)?'':'none'})}
const net=()=>{const n=$('#net');n.textContent=navigator.onLine?'Online':'Offline';n.className='pill '+(navigator.onLine?'on':'off')};
addEventListener('online',net);addEventListener('offline',net);addEventListener('hashchange',()=>{const h=location.hash.slice(1);if(V[h]&&h!=page){page=h;render()}});
$('#menu').onclick=()=>$('#side').classList.toggle('open');$('#q').oninput=filter;
(async()=>{try{await open_();await load();if(!D.settings.some(x=>x.id=='profile')){await put('settings',P);await loadServices()}net();page=V[location.hash.slice(1)]?location.hash.slice(1):'dashboard';render();if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js')}catch(e){document.body.innerHTML='<p style="padding:20px">Storage unavailable: '+e.message+'</p>'}})();
